### PR TITLE
chore: bump minimum required Deno version to 1.46.0 and cleanup

### LINKED ISSUE #328: deployctl does not work with Deno 2.0 RC version
We get type errors when we run deployctl with Deno 2.0 RC version:

```
error: TS2339 [ERROR]: Property 'isatty' does not exist on type 'typeof Deno'.
      Deno.isatty(stream.rid) &&
           ~~~~~~
    at file:///Users/runner/work/deployctl/deployctl/vendor/deno.land/x/tty@0.1.4/is_interactive.ts:4:12

TS2339 [ERROR]: Property 'isatty' does not exist on type 'typeof Deno'.
  return Deno.isatty(stream.rid);
              ~~~~~~
    at file:///Users/runner/work/deployctl/deployctl/vendor/deno.land/x/tty@0.1.4/is_interactive.ts:9:15

TS2339 [ERROR]: Property 'isatty' does not exist on type 'typeof Deno'.
  return Deno.isatty(stream.rid);
              ~~~~~~
    at file:///Users/runner/work/deployctl/deployctl/vendor/deno.land/x/tty@0.1.4/is_interactive.ts:13:15

Found 3 errors.
```

https://github.com/denoland/deployctl/actions/runs/10715041741/job/29709772144?pr=313#step:8:205

### PR DESCRIPTION
**Pull request by magurotuna**
This commit bumps the minimum required Deno version to 1.46.0 and cleanups the code mainly to deal with deprecated Deno APIs.

Fixes #328

### CODE REVIEW

**Comment by magurotuna** [comment]
Blocked by https://github.com/denoland/deno_emit/issues/167 as deployctl relies on `@deno/emit` to transpile TS code into JS so it can be run as GitHub Actions action.

File: src/utils/mod.ts [hunk 1]
```diff
@@ -1,21 +1,4 @@
...
-      semverParse(Deno.version.deno),
-      semverParse("1.40.0"),
-    )
-  ) {
-    return stream.isTerminal();
-  } else {
-    // deno-lint-ignore no-deprecated-deno-api
-    return Deno.isatty(stream.rid);
-  }
-}
```
Comment (magurotuna) [inline src/utils/mod.ts:21]: For reviewers: `isTerminal` method on various stream types is available on 1.40.0+ and our minimum required Deno version is now 1.46.0. We don't have to polyfill anymore.

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -15,7 +15,10 @@ jobs:
       matrix:
         # Test on the oldest supported, the latest stable, and nightly
         deno: [old, stable, canary]
-        os: [macOS-latest, windows-latest, ubuntu-22.04-xl]
+        os: [macOS-latest, windows-latest, ubuntu-latest]
+
+    env:
+      DENO_FUTURE: ${{ matrix.deno == 'old' && '1' || '0' }}
```
Comment (arnauorriols) [inline .github/workflows/ci.yml:21]: Why run the old with DENO_FUTURE=1?

File: src/error.ts [hunk 3]
```diff
@@ -1,10 +1,33 @@
...
+    return err;
+  }
+
+  return JSON.stringify(err, null, 2);
+}
+
+function stringifyError(err: Error): string {
+  const cause = err.cause === undefined
+    ? ""
+    : `Caused by ${stringify(err.cause)}`;
```
Comment (arnauorriols) [inline src/error.ts:26]: Maybe add the new line in here, this way we don't get an empty line if there's no cause.

Having said that, being a CLI tool, deployctl is sensible to changes in the formatting of the error messages. I'm a bit concerned that adding this newline will break the formatting here and there inadvertently. Maybe we could use  parenthesis `(${cause})` instead of new line `\n${cause}`?

File: src/utils/access_token.ts [hunk 4]
```diff
@@ -76,7 +77,7 @@ async function provision(): Promise<string> {
       wait("").start().warn(
         "Unexpected error while trying to open the authorization URL in your default browser. Please report it at https://github.com/denoland/deployctl/issues/new.",
       );
-      wait({ text: "", indent: 3 }).start().fail(error.toString());
+      wait({ text: "", indent: 3 }).start().fail(stringifyError(error));
```
Comment (arnauorriols) [inline src/utils/access_token.ts:80]: Can you check if this change breaks the output format? IIRC it was sensible to multiline error messages.

**Review by arnauorriols — COMMENTED** [review]
Added some comments

**Comment by arnauorriols** [comment]
Also make sure to update the README with the new minimum version

File: .github/workflows/ci.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (magurotuna) [reply .github/workflows/ci.yml:21]: This is needed to enable support for lockfile v4.

File: src/error.ts (hunk 3 above)
Comment (magurotuna) [reply src/error.ts:26]: Can you elaborate a bit more on why CLI tools are sensible to the change of error message formats? 

> Maybe we could use parenthesis (${cause}) instead of new line \n${cause}?

Parenthesis sounds good, but the next problem is that `cause` itself might contain newline characters in it. I'll try to replace them (if any) with white spaces.

File: src/utils/access_token.ts (hunk 4 above)
Comment (magurotuna) [reply src/utils/access_token.ts:80]: If an error is formatted in a multi-line format, it is printed like this:

CleanShot 2024-10-18 at 20 29 43@2x

This error instance is created as follows:

```ts
    const e1 = new Error("This is\na multiline\nerror");
    const e2 = new Error("e2", { cause: e1 });
    throw e2;
```

I am not sure if I understand your concern, but does this look concerning to you?

File: .github/workflows/ci.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (arnauorriols) [reply .github/workflows/ci.yml:21]: It's a bit weird to test with DENO_FUTURE=1, it defeats the purpose of testing with 1.46

File: src/utils/access_token.ts (hunk 4 above)
Comment (arnauorriols) [reply src/utils/access_token.ts:80]: It's purposedly identated and kept in a single line because it is not a hard error, the program continues. If the error breaks this identation then it breaks the output layout.

File: src/error.ts (hunk 3 above)
Comment (arnauorriols) [reply src/error.ts]: There are places where the error is not fatal, and should be shown to the user intertwined with regular output. If the error has multiple lines it breaks the output layout. One example is https://github.com/denoland/deployctl/pull/332#discussion_r1806424870

File: .github/workflows/ci.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (magurotuna) [reply .github/workflows/ci.yml:21]: That kinda makes sense - Would you agree to bump the minimum required version to 2.0?

[the remark this answers is not in the document]
Comment (arnauorriols) [reply .github/workflows/ci.yml:21]: Maybe we can test with --no-lock when testing with 1.X?

[the remark this answers is not in the document]
Comment (magurotuna) [reply .github/workflows/ci.yml:21]: I tried that now, but turned out it's actually involved, because test cases in [help_test.ts](https://github.com/denoland/deployctl/blob/8644ec52d28f9f9c57d30535f4a1a2a93cc9f093/tests/help_test.ts) spawn another Deno process to run `deployctl.ts` and we need to pass `--no-lock` to it but `Deno.args` is an empty array when running `deno test`.

File: src/error.ts (hunk 3 above)
Comment (magurotuna) [reply src/error.ts]: That makes lots of sense. I'll create another function to stringify errors in a simple, one-line format rather than full verbose ones so we can use it in non-fatal places.

File: src/utils/access_token.ts (hunk 4 above)
Comment (magurotuna) [reply src/utils/access_token.ts:80]: Now `stringifyError(error)` returns a simple one-line error message while `stringifyError(error, { verbose: true })` generates a full detailed output.

File: src/error.ts (hunk 3 above)
Comment (magurotuna) [reply src/error.ts]: Now `stringify` function gets `verbose` option which defaults to `false`. If an error is printed when the deployctl program keeps running, simple message is displayed. Otherwise i.e. when the program exits right after the error message is printed, verbose message is generated.

File: .github/workflows/ci.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (magurotuna) [reply .github/workflows/ci.yml]: I did a hacky approach in [3e0d9a0](https://github.com/denoland/deployctl/pull/332/commits/3e0d9a08da1c5cb19bf7da030f1e9a2c8cf14c36) where `--no-lock` is appended based on the semver comparison.

**Review by arnauorriols — APPROVED** [review]
LGTM!
